version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    - ./docker/mysql/config:/etc/mysql/conf.d
    - ./docker/mysql/init:/docker-entrypoint-initdb.d